"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/Sidebar";
type Customer={id:string;name:string;phone:string|null;location:string|null};
type Activity={id:string;occurredAt:string;summary:string;outcome:string|null;customer:{id:string;name:string}};
function formatDate(v:string){return new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}
function initials(n:string){return n.split(/\s+/).slice(0,2).map(x=>x[0]??"").join("").toUpperCase();}
export default function CallsPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[calls,setCalls]=useState<Activity[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [cr,ar]=await Promise.all([fetch("/api/customers",{cache:"no-store"}),fetch("/api/activities?limit=100",{cache:"no-store"})]);const [c,a]=await Promise.all([cr.json(),ar.json()]);if(!cr.ok)throw new Error(c.message??"Müşteriler alınamadı.");if(!ar.ok)throw new Error(a.message??"Aramalar alınamadı.");setCustomers(c.customers??[]);setCalls((a.activities??[]).filter((x:Activity)=>x.customer));}catch(e){setError(e instanceof Error?e.message:"Arama verileri alınamadı.");}finally{setLoading(false);}}
 // Data fetching synchronizes React state with external API data.\n // eslint-disable-next-line react-hooks/set-state-in-effect\n useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("tr-TR");return customers.filter(c=>!q||[c.name,c.phone??"",c.location??""].join(" ").toLocaleLowerCase("tr-TR").includes(q));},[customers,query]);
 const today=new Date().toDateString(),todayCalls=calls.filter(c=>new Date(c.occurredAt).toDateString()===today);
 return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar/><main className="min-w-0 flex-1"><div className="mx-auto max-w-7xl px-3 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">CRM · Calls</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Aramalar</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Telefon görüşmesini kayda dönüştürün; müşteri geçmişi ve sonraki aksiyon aynı akışta kalsın.</p></div><div className="grid w-full grid-cols-1 gap-2 sm:flex sm:w-auto">
  <Link href="/sales/activity/new?type=ARAMA" className="w-full rounded-xl bg-slate-950 px-4 py-3 text-center text-sm font-semibold text-white sm:w-auto">+ Arama Kaydı</Link><button onClick={()=>void load()} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-center text-sm font-semibold text-slate-700 sm:w-auto">↻ Yenile</button></div></header>
  {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <section className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Bugünkü aramalar</p><p className="mt-2 text-2xl font-semibold">{loading?"—":todayCalls.length}</p></div><div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Toplam kayıt</p><p className="mt-2 text-2xl font-semibold">{loading?"—":calls.length}</p></div><div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Müşteri</p><p className="mt-2 text-2xl font-semibold">{loading?"—":customers.length}</p></div></section>
  <section className="mt-6 grid gap-5 lg:grid-cols-[360px_minmax(0,1fr)]"><div className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="border-b border-slate-100 p-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Müşteri ara…" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none"/></div><div className="max-h-[72vh] overflow-y-auto divide-y divide-slate-100">{loading?<p className="p-5 text-sm text-slate-500">Müşteriler yükleniyor…</p>:filtered.map(c=><div key={c.id} className="grid grid-cols-[40px_minmax(0,1fr)] items-center gap-3 p-4 sm:flex"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">{initials(c.name)}</div><div className="min-w-0 sm:flex-1"><p className="truncate font-semibold">{c.name}</p><p className="mt-1 truncate text-xs text-slate-500">{c.location??"Konum belirtilmemiş"}</p></div><div className="col-span-2 grid grid-cols-2 gap-2 sm:col-span-1 sm:flex">{c.phone?<a href={"tel:"+c.phone} className="rounded-xl bg-slate-100 px-3 py-2.5 text-center text-sm font-semibold text-slate-700">Ara</a>:<span className="rounded-xl bg-slate-50 px-3 py-2.5 text-center text-xs text-slate-400">Telefon yok</span>}<Link href={"/sales/activity/new?customerId="+encodeURIComponent(c.id)+"&type=ARAMA"} className="rounded-xl bg-slate-900 px-3 py-2.5 text-center text-xs font-semibold text-white">Kaydet</Link></div></div>)}</div></div>
  <div className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Arama geçmişi</p><h2 className="mt-1 text-xl font-semibold">Son görüşmeler</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-500">{calls.length} kayıt</span></div><div className="mt-5 space-y-3">{calls.map(c=><article key={c.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><Link href={"/clients/"+c.customer.id} className="font-semibold text-slate-900 hover:underline">{c.customer.name}</Link><p className="mt-1 text-xs text-slate-400">{formatDate(c.occurredAt)}</p></div><Link href={"/sales/activity/new?customerId="+encodeURIComponent(c.customer.id)+"&type=ARAMA"} className="text-xs font-semibold text-slate-700">Yeni arama kaydı →</Link></div><p className="mt-3 text-sm font-medium text-slate-800">{c.summary}</p>{c.outcome&&<p className="mt-1 text-xs leading-5 text-slate-500">{c.outcome}</p>}</article>)}{!loading&&!calls.length&&<div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">Henüz arama kaydı yok.</div>}</div></div></section>
 </div></main></div>;
}