"use client";
import { useEffect,useState } from "react";
type App={id:string;officeName:string;ownerFirstName:string;ownerLastName:string;ownerEmail:string;ownerPhone:string;status:string;rejectionNote:string|null;createdAt:string};
export default function PlatformOfficeApplications(){
 const [apps,setApps]=useState<App[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch("/api/platform/office-applications",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setApps(d.applications||[]);}catch(e){setError(e instanceof Error?e.message:"Yüklenemedi.");}finally{setLoading(false);}}
 useEffect(()=>{void load()},[]);
 async function action(id:string,action:"APPROVE"|"REJECT"){setError("");const note=action==="REJECT"?window.prompt("Red nedeni (opsiyonel):")||"":"";const r=await fetch("/api/platform/office-applications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action,rejectionNote:note})});const d=await r.json();if(!r.ok){setError(d.message||"İşlem başarısız.");return;}await load();}
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">PrimeEstate · Platform</p><div className="mt-2 flex items-end justify-between"><div><h1 className="text-3xl font-bold text-slate-950">Ofis Başvuruları</h1><p className="mt-2 text-sm text-slate-500">Platforma katılmak isteyen ofisleri buradan onaylayın.</p></div></div>{error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading?<div className="mt-6 rounded-2xl bg-white p-8 text-sm text-slate-500">Başvurular yükleniyor…</div>:<div className="mt-6 space-y-3">{apps.length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">Henüz başvuru yok.</div>:apps.map(a=><article key={a.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold text-slate-950">{a.officeName}</h2><p className="mt-1 text-sm text-slate-600">{a.ownerFirstName} {a.ownerLastName} · {a.ownerPhone}</p><p className="mt-1 text-sm text-slate-500">{a.ownerEmail}</p><p className="mt-2 text-xs text-slate-400">{new Date(a.createdAt).toLocaleString("tr-TR")} · {a.status}</p></div>{a.status==="BEKLEMEDE"&&<div className="flex gap-2"><button onClick={()=>void action(a.id,"REJECT")} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Reddet</button><button onClick={()=>void action(a.id,"APPROVE")} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Onayla</button></div>}</div></article>)}</div>}</div></main>;
}