"use client";

import { useEffect,useState } from "react";
import Sidebar from "@/components/Sidebar";

type App={id:string;firstName:string;lastName:string;tcIdentityNumber:string;email:string;phone:string;companyName:string;companyTitle:string|null;companyTaxNumber:string|null;companyPhone:string|null;companyEmail:string|null;commissionModel:string;officeShareRate:string|null;consultantShareRate:string|null;status:string;rejectionNote:string|null;createdAt:string};

export default function ConsultantApplicationsPage(){
 const [apps,setApps]=useState<App[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/consultant-applications",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setApps(d.applications||[]);}catch(e){setError(e instanceof Error?e.message:"Başvurular yüklenemedi.");}finally{setLoading(false);}}
 useEffect(()=>{void load()},[]);
 async function action(id:string,action:"APPROVE"|"REJECT"){setBusy(id);setError("");const note=action==="REJECT"?window.prompt("Red nedeni (opsiyonel):")||"":"";try{const r=await fetch("/api/consultant-applications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action,rejectionNote:note})});const d=await r.json();if(!r.ok)throw new Error(d.message);await load();}catch(e){setError(e instanceof Error?e.message:"İşlem başarısız.");}finally{setBusy("");}}
 return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar/><main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">PrimeEstate · Broker</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Danışman Başvuruları</h1><p className="mt-2 text-sm text-slate-500">Ofisinize katılmak isteyen danışmanları inceleyin ve onaylayın.</p>{error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading?<div className="mt-6 rounded-2xl bg-white p-8 text-sm text-slate-500">Başvurular yükleniyor…</div>:<div className="mt-6 space-y-4">{apps.length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">Henüz danışman başvurusu yok.</div>:apps.map(a=><article key={a.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-950">{a.firstName} {a.lastName}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{a.status}</span></div><div className="mt-3 grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><div>E-posta: {a.email}</div><div>Telefon: {a.phone}</div><div>T.C. Kimlik: {a.tcIdentityNumber}</div><div>Şirket: {a.companyName}</div><div>Şirket unvanı: {a.companyTitle||"—"}</div><div>Vergi no: {a.companyTaxNumber||"—"}</div><div>Komisyon: {a.commissionModel}</div><div>Ofis payı: {a.officeShareRate ? "%"+a.officeShareRate : "—"}</div><div>Danışman payı: {a.consultantShareRate ? "%"+a.consultantShareRate : "—"}</div></div><p className="mt-3 text-xs text-slate-400">Başvuru: {new Date(a.createdAt).toLocaleString("tr-TR")}</p></div>{a.status==="BEKLEMEDE"&&<div className="flex gap-2 lg:self-center"><button disabled={busy===a.id} onClick={()=>void action(a.id,"REJECT")} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Reddet</button><button disabled={busy===a.id} onClick={()=>void action(a.id,"APPROVE")} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Onayla</button></div>}</div></article>)}</div>}</div></main></div>;
}
