"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/Sidebar";

type Sale = { id:string; amount:string|number; currency:string; status:string; customer:{id:string;name:string}; listing:{code:string;title:string} };
type Installment = { id:string; sequence:number; amount:string|number; currency:string; dueAt:string; status:"BEKLIYOR"|"ODENDI"|"IPTAL"; note:string|null };
type Plan = { id:string; title:string; currency:string; installments:Installment[]; sale:Sale };

const money=(v:string|number,c:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c}).format(Number(v));
const dueLabel=(d:string,status:string,nowMs:number)=>status==="ODENDI"?"Ödendi":status==="IPTAL"?"İptal":Date.parse(d)<nowMs?"Vadesi geçti":"Bekliyor";

export default function FinanceDashboard(){
 const [sales,setSales]=useState<Sale[]>([]),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(""),[nowMs,setNowMs]=useState(0);
 async function load(){setLoading(true);try{const [s,p]=await Promise.all([fetch("/api/sales"),fetch("/api/payment-plans")]);const sj=await s.json(),pj=await p.json();if(!s.ok)throw new Error(sj.message);if(!p.ok)throw new Error(pj.message);setSales(sj.sales);setPlans(pj.plans)}catch(e){setError(e instanceof Error?e.message:"Finans verileri yüklenemedi.")}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>{setNowMs(Date.now());void load()},0);return()=>clearTimeout(t)},[]);
 const stats=useMemo(()=>{let due=0,over=0,paid=0;const byCurrency:Record<string,{due:number;over:number;paid:number}>={};for(const p of plans)for(const i of p.installments){const c=i.currency;(byCurrency[c]??={due:0,over:0,paid:0});if(i.status==="ODENDI"){paid+=Number(i.amount);byCurrency[c].paid+=Number(i.amount)}else if(i.status==="BEKLIYOR"){due+=Number(i.amount);byCurrency[c].due+=Number(i.amount);if(Date.parse(i.dueAt)<nowMs){over+=Number(i.amount);byCurrency[c].over+=Number(i.amount)}}}return{due,over,paid,byCurrency}},[plans,nowMs]);
 async function status(id:string,status:"BEKLIYOR"|"ODENDI"|"IPTAL"){setSaving(id);try{const r=await fetch("/api/payment-installments/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const j=await r.json();if(!r.ok)throw new Error(j.message);setPlans(x=>x.map(p=>({...p,installments:p.installments.map(i=>i.id===id?j.installment:i)})))}catch(e){setError(e instanceof Error?e.message:"Taksit güncellenemedi.")}finally{setSaving("")}}
 async function createPlan(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);const saleId=String(f.get("saleId")||"");const count=Number(f.get("count")||1);const amount=Number(f.get("amount")||0);const first=String(f.get("firstDue")||"");const title=String(f.get("title")||"");if(!saleId||!count||!amount||!first||!title)return;const rows=Array.from({length:count},(_,idx)=>{const d=new Date(first);d.setMonth(d.getMonth()+idx);return{amount,dueAt:d.toISOString()}});try{const r=await fetch("/api/payment-plans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({saleId,title,installments:rows})});const j=await r.json();if(!r.ok)throw new Error(j.message);await load();e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"Plan oluşturulamadı.")}}
 return <div className="min-h-screen bg-slate-50"><Sidebar/><main className="md:pl-64"><div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Finance V7</p><h1 className="text-2xl font-semibold text-slate-950">Cari & Ödeme Planı</h1><p className="mt-1 text-sm text-slate-500">Tahsilat, vade ve ofis/danışman cari hareketlerini tek ekranda takip edin.</p></div><a href="/finance" className="text-sm font-semibold text-slate-700 underline">Komisyon & Tahsilat</a></div>
 <section className="mt-6 grid gap-3 sm:grid-cols-3">{[["Bekleyen",stats.due],["Vadesi geçen",stats.over],["Ödenen",stats.paid]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs text-slate-400">{k}</p><p className="mt-1 text-2xl font-semibold text-slate-950">{Number(v).toLocaleString("tr-TR",{maximumFractionDigits:2})}</p><p className="mt-1 text-xs text-slate-400">Para birimine göre aşağıda</p></div>)}</section>
 <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">Para birimi özeti</h2><div className="mt-3 grid gap-3 sm:grid-cols-3">{Object.entries(stats.byCurrency).map(([c,v])=><div key={c} className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold">{c}</p><p className="mt-2 text-xs text-slate-500">Bekleyen: <b>{money(v.due,c)}</b></p><p className="text-xs text-rose-600">Vadesi geçen: <b>{money(v.over,c)}</b></p><p className="text-xs text-emerald-600">Ödenen: <b>{money(v.paid,c)}</b></p></div>)}</div></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Yeni ödeme planı</h2><p className="mt-1 text-xs text-slate-500">Taksit toplamı satış tutarına eşit olmalıdır.</p><form onSubmit={createPlan} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select name="saleId" required className="rounded-xl border p-3"><option value="">Satış seçin</option>{sales.filter(s=>s.status!=="IPTAL").map(s=><option key={s.id} value={s.id}>{s.customer.name} · {s.listing.code} · {money(s.amount,s.currency)}</option>)}</select><input name="title" required placeholder="Örn. 3 aylık ödeme planı" className="rounded-xl border p-3"/><input name="count" required min="1" max="24" type="number" defaultValue="3" className="rounded-xl border p-3"/><input name="amount" required min="0.01" step="0.01" type="number" placeholder="Taksit tutarı" className="rounded-xl border p-3"/><input name="firstDue" required type="date" className="rounded-xl border p-3"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white sm:col-span-2 lg:col-span-5">Planı oluştur</button></form></section>
 <section className="mt-6 space-y-4">{loading?<div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-400">Yükleniyor…</div>:plans.map(p=><article key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{p.title}</h2><p className="text-sm text-slate-500">{p.sale.customer.name} · {p.sale.listing.code} · {money(p.sale.amount,p.sale.currency)}</p></div><span className="text-xs text-slate-400">{p.installments.length} taksit</span></div><div className="mt-4 space-y-2">{p.installments.map(i=><div key={i.id} className="flex flex-col gap-2 rounded-xl bg-slate-50 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{i.sequence}. taksit · {money(i.amount,i.currency)}</p><p className="text-xs text-slate-500">Vade: {new Date(i.dueAt).toLocaleDateString("tr-TR")} · {dueLabel(i.dueAt,i.status,nowMs)}</p></div><div className="flex gap-2">{i.status==="BEKLIYOR"&&<><button disabled={saving===i.id} onClick={()=>void status(i.id,"ODENDI")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Ödendi</button><button disabled={saving===i.id} onClick={()=>void status(i.id,"IPTAL")} className="rounded-lg border px-3 py-2 text-xs font-semibold">İptal</button></>}{i.status!=="BEKLIYOR"&&<button disabled={saving===i.id} onClick={()=>void status(i.id,"BEKLIYOR")} className="rounded-lg border px-3 py-2 text-xs font-semibold">Bekleyene al</button>}</div></div>)}</div></article>)}</section>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}</div></main></div>
}
