"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/Sidebar";

type Customer={id:string;name:string;phone:string|null;email:string|null;location:string|null;relationshipScore:number;lastContactAt:string|null;nextAction:string|null;nextActionAt:string|null;roles:{role:string}[];demands:{id:string;title:string;type:string;propertyType:string;urgency:string}[];owner:{id:string;name:string;email:string}};
type Activity={id:string;type:string;occurredAt:string;summary:string;outcome:string|null;customer:{id:string;name:string}};
type Task={id:string;title:string;dueAt:string;priority:string;status:string;customer:{id:string;name:string}|null};
type Showing={id:string;dateTime:string;status:string;attendees:number;note:string|null;customer:{id:string;name:string};listing:{id:string;code:string;title:string;price:string|number;currency:string;property:{city:string;district:string;neighborhood:string}}};
type Offer={id:string;amount:string|number;currency:string;status:string;offeredAt:string;nextAction:string|null;customer:{id:string;name:string};listing:{id:string;code:string;title:string;price:string|number;currency:string}};
type Sale={id:string;amount:string|number;currency:string;status:string;createdAt:string;closedAt:string|null;customer:{id:string;name:string};listing:{id:string;code:string;title:string;status:string;purpose:string};offer:{id:string;status:string}};
const roleMap:Record<string,string>={ALICI:"Alıcı",KIRACI:"Kiracı",MAL_SAHIBI:"Mal Sahibi",SATICI:"Satıcı",YATIRIMCI:"Yatırımcı",LEAD:"Lead",GECMIS_MUSTERI:"Geçmiş Müşteri"};
const activityMap:Record<string,string>={ARAMA:"Arama",WHATSAPP:"WhatsApp",EMAIL:"E-posta",NOT:"Not",GOSTERIM:"Gösterim",TEKLIF:"Teklif"};
const priorityMap:Record<string,string>={YUKSEK:"Yüksek",NORMAL:"Normal",DUSUK:"Düşük"};
function date(v:string|null){return v?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Henüz yok";}
function initials(n:string){return n.split(/\s+/).slice(0,2).map(x=>x[0]??"").join("").toUpperCase();}
export default function RelationshipsPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[activities,setActivities]=useState<Activity[]>([]),[tasks,setTasks]=useState<Task[]>([]),[showings,setShowings]=useState<Showing[]>([]),[offers,setOffers]=useState<Offer[]>([]),[sales,setSales]=useState<Sale[]>([]);
 const [selectedId,setSelectedId]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [cr,ar,tr,sr,or,salr]=await Promise.all([fetch("/api/customers",{cache:"no-store"}),fetch("/api/activities?limit=100",{cache:"no-store"}),fetch("/api/tasks?limit=100",{cache:"no-store"}),fetch("/api/showings",{cache:"no-store"}),fetch("/api/offers",{cache:"no-store"}),fetch("/api/sales",{cache:"no-store"})]);const [c,a,t,sh,o,sal]=await Promise.all([cr.json(),ar.json(),tr.json(),sr.json(),or.json(),salr.json()]);if(!cr.ok)throw new Error(c.message??"Müşteriler alınamadı.");if(!ar.ok)throw new Error(a.message??"Aktiviteler alınamadı.");if(!tr.ok)throw new Error(t.message??"Görevler alınamadı.");if(!sr.ok)throw new Error(sh.message??"Gösterimler alınamadı.");if(!or.ok)throw new Error(o.message??"Teklifler alınamadı.");if(!salr.ok)throw new Error(sal.message??"Satışlar alınamadı.");const next=c.customers??[];setCustomers(next);setActivities(a.activities??[]);setTasks(t.tasks??[]);setShowings(sh.showings??[]);setOffers(o.offers??[]);setSales(sal.sales??[]);setSelectedId(current=>current&&next.some((x:Customer)=>x.id===current)?current:next[0]?.id??"");}catch(e){setError(e instanceof Error?e.message:"İlişki verileri alınamadı.");}finally{setLoading(false);}}
 // Data fetching synchronizes React state with external API data.\n // eslint-disable-next-line react-hooks/set-state-in-effect\n useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase("tr-TR");return customers.filter(c=>!q||[c.name,c.phone??"",c.email??"",c.location??"",...c.roles.map(r=>roleMap[r.role]??r.role)].join(" ").toLocaleLowerCase("tr-TR").includes(q));},[customers,query]);
 const selected=customers.find(c=>c.id===selectedId)??null, customerActivities=activities.filter(a=>a.customer.id===selectedId), customerTasks=tasks.filter(t=>t.customer?.id===selectedId), customerShowings=showings.filter(x=>x.customer.id===selectedId), customerOffers=offers.filter(x=>x.customer.id===selectedId), customerSales=sales.filter(x=>x.customer.id===selectedId), openTasks=tasks.filter(t=>t.status!=="TAMAMLANDI").length;
 return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar/><main className="min-w-0 flex-1"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">CRM · Relationship Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">İlişkiler</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Müşterinin kim olduğunu, en son ne yaşandığını ve sıradaki aksiyonu tek çalışma alanında yönetin.</p></div><div className="flex flex-wrap gap-2"><Link href="/sales/activity/new" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">+ Aktivite</Link><Link href="/sales/task/new" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">+ Görev</Link><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">↻ Yenile</button></div></header>
  {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <section className="mt-6 grid gap-3 sm:grid-cols-3">{[["Müşteri",customers.length],["Açık görev",openTasks],["Son aktiviteler",activities.length]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{loading?"—":value}</p></div>)}</section>
  <section className="mt-6 grid gap-5 lg:grid-cols-[360px_minmax(0,1fr)]">
   <div className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="border-b border-slate-100 p-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Müşteri ara…" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none focus:border-slate-400"/></div><div className="max-h-[72vh] overflow-y-auto divide-y divide-slate-100">{loading?<p className="p-5 text-sm text-slate-500">Müşteriler yükleniyor…</p>:filtered.map(c=><button key={c.id} type="button" onClick={()=>setSelectedId(c.id)} className={"w-full p-4 text-left hover:bg-slate-50 "+(selectedId===c.id?"bg-slate-50":"")}><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-900 text-xs font-bold text-white">{initials(c.name)}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate font-semibold text-slate-900">{c.name}</p><span className="text-xs font-semibold text-slate-500">{c.relationshipScore}</span></div><p className="mt-1 truncate text-xs text-slate-500">{c.location??"Konum belirtilmemiş"}</p><div className="mt-2 flex flex-wrap gap-1">{c.roles.slice(0,2).map(r=><span key={r.role} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{roleMap[r.role]??r.role}</span>)}</div></div></div></button>)}{!loading&&!filtered.length&&<p className="p-6 text-center text-sm text-slate-500">Müşteri bulunamadı.</p>}</div></div>
   {selected?<div className="space-y-5"><div className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10 font-bold">{initials(selected.name)}</div><div><p className="text-xs uppercase tracking-[0.16em] text-slate-400">Müşteri</p><h2 className="mt-1 text-2xl font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-slate-300">{selected.phone??"Telefon yok"} · {selected.email??"E-posta yok"}</p></div></div><div className="flex gap-2"><Link href={"/clients/"+selected.id} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Müşteriyi Aç</Link>{selected.phone&&<a href={"tel:"+selected.phone} className="rounded-xl bg-white/10 px-4 py-2.5 text-sm font-semibold text-white">Ara</a>}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">İlişki skoru</p><p className="mt-1 text-2xl font-semibold">{selected.relationshipScore}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Son temas</p><p className="mt-1 text-sm font-semibold">{date(selected.lastContactAt)}</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Sonraki aksiyon</p><p className="mt-1 text-sm font-semibold">{selected.nextAction??"Belirlenmedi"}</p></div></div></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Aktivite geçmişi</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{customerActivities.length} kayıt</h3></div><Link href={"/sales/activity/new?customerId="+encodeURIComponent(selected.id)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">+ Aktivite</Link></div><div className="mt-4 space-y-3">{customerActivities.slice(0,8).map(a=><div key={a.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-slate-900">{activityMap[a.type]??a.type}</p><span className="text-xs text-slate-400">{date(a.occurredAt)}</span></div><p className="mt-2 text-sm text-slate-700">{a.summary}</p>{a.outcome&&<p className="mt-1 text-xs text-slate-500">{a.outcome}</p>}</div>)}{!customerActivities.length&&<p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Bu müşteride henüz aktivite yok.</p>}</div></section>
     <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Görevler</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{customerTasks.length} kayıt</h3></div><Link href={"/sales/task/new?customerId="+encodeURIComponent(selected.id)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">+ Görev</Link></div><div className="mt-4 space-y-3">{customerTasks.slice(0,8).map(t=><div key={t.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-slate-900">{t.title}</p><span className="text-xs text-slate-400">{date(t.dueAt)}</span></div><div className="mt-2 flex gap-2 text-xs"><span className="rounded-full bg-white px-2 py-1 text-slate-600">{priorityMap[t.priority]??t.priority}</span><span className="rounded-full bg-white px-2 py-1 text-slate-600">{t.status==="TAMAMLANDI"?"Tamamlandı":"Açık"}</span></div></div>)}{!customerTasks.length&&<p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Bu müşteride henüz görev yok.</p>}</div></section></div>
    <div className="grid gap-5 xl:grid-cols-2">
     <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Gösterimler</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{customerShowings.length} kayıt</h3></div><Link href={"/sales/showing/new?customerId="+encodeURIComponent(selected.id)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">+ Gösterim</Link></div><div className="mt-4 space-y-3">{customerShowings.slice(0,8).map(x=><Link key={x.id} href="/sales" className="block rounded-2xl bg-slate-50 p-4 hover:bg-slate-100"><div className="flex justify-between gap-3"><p className="font-semibold text-slate-900">{x.listing.code} · {x.listing.title}</p><span className="text-xs text-slate-400">{date(x.dateTime)}</span></div><p className="mt-1 text-xs text-slate-500">{x.listing.property.district} · {x.listing.property.neighborhood} · {x.status==="GERCEKLESTI"?"Gerçekleşti":x.status==="IPTAL"?"İptal":"Planlandı"}</p></Link>)}{!customerShowings.length&&<p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Bu müşteride henüz gösterim yok.</p>}</div></section>
     <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Teklifler</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{customerOffers.length} kayıt</h3></div><Link href={"/sales/offer/new?customerId="+encodeURIComponent(selected.id)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">+ Teklif</Link></div><div className="mt-4 space-y-3">{customerOffers.slice(0,8).map(x=><Link key={x.id} href="/sales" className="block rounded-2xl bg-slate-50 p-4 hover:bg-slate-100"><div className="flex justify-between gap-3"><p className="font-semibold text-slate-900">{x.listing.code} · {x.listing.title}</p><span className="text-sm font-semibold text-slate-900">{new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0}).format(Number(x.amount))} {x.currency}</span></div><p className="mt-1 text-xs text-slate-500">{x.status==="KABUL"?"Kabul":x.status==="REDDEDILDI"?"Reddedildi":x.status==="SUNULDU"?"Sunuldu":x.status==="KARSILIKLI_TEKLIF"?"Karşılıklı teklif":"Taslak"} · {date(x.offeredAt)}</p></Link>)}{!customerOffers.length&&<p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Bu müşteride henüz teklif yok.</p>}</div></section>
    </div>
    <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Satışlar</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{customerSales.length} kayıt</h3></div></div><div className="mt-4 space-y-3">{customerSales.map(x=><Link key={x.id} href={"/sales/"+x.id} className="block rounded-2xl bg-slate-50 p-4 hover:bg-slate-100"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{x.listing.code} · {x.listing.title}</p><p className="mt-1 text-xs text-slate-500">{x.status==="TAMAMLANDI"?"Tamamlandı":x.status==="IPTAL"?"İptal":"Açık"} · {date(x.closedAt??x.createdAt)}</p></div><p className="font-semibold text-slate-900">{new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0}).format(Number(x.amount))} {x.currency}</p></div></Link>)}{!customerSales.length&&<p className="rounded-2xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">Bu müşteride henüz satış yok.</p>}</div></section>
    <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Aktif talepler</p><h3 className="mt-1 text-xl font-semibold text-slate-950">{selected.demands.length} talep</h3></div><Link href={"/clients/"+selected.id} className="text-sm font-semibold text-slate-700">Müşteri detayına git →</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2">{selected.demands.map(d=><div key={d.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold text-slate-900">{d.title}</p><p className="mt-1 text-xs text-slate-500">{d.type} · {d.propertyType} · Aciliyet: {d.urgency}</p></div>)}{!selected.demands.length&&<p className="text-sm text-slate-500">Aktif talep bulunmuyor.</p>}</div></section>
   </div>:<div className="rounded-3xl bg-white p-10 text-center text-sm text-slate-500">Müşteri seçin.</div>}
  </section>
 </div></main></div>;
}