"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import Sidebar from "@/components/Sidebar";
type Customer={id:string;name:string};
export default function NewSalesTaskPage(){
 const router=useRouter();const [customers,setCustomers]=useState<Customer[]>([]),[customerId,setCustomerId]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("customerId"))setCustomerId(p.get("customerId")!);fetch("/api/customers",{cache:"no-store"}).then(r=>r.json()).then(d=>setCustomers(d.customers??[])).catch(()=>setError("Müşteriler alınamadı."));},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget).entries());try{const r=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.message??"Görev oluşturulamadı.");router.push("/relationships");}catch(err){setError(err instanceof Error?err.message:"Görev oluşturulamadı.");setSaving(false);}}
 return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar/><main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-3xl"><button type="button" onClick={()=>router.back()} className="mb-5 text-sm font-semibold text-slate-600">← Geri</button><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">CRM · Takip</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Yeni Görev</h1><p className="mt-2 text-sm text-slate-500">Bir sonraki aksiyonu tarih ve önceliğiyle kaydet.</p></header>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Müşteri</span><select name="customerId" value={customerId} onChange={e=>setCustomerId(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Müşteri seçmeden devam et</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Görev *</span><input required name="title" autoFocus placeholder="Örn. Cuma günü müşteriyi ara" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><label className="block"><span className="text-sm font-semibold text-slate-700">Son tarih *</span><input required name="dueAt" type="datetime-local" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><label className="block"><span className="text-sm font-semibold text-slate-700">Öncelik</span><select name="priority" defaultValue="NORMAL" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="YUKSEK">Yüksek</option><option value="NORMAL">Normal</option><option value="DUSUK">Düşük</option></select></label><label className="block sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Kaynak</span><input name="source" defaultValue="RELATIONSHIP_WORKSPACE" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label></div></section><div className="flex justify-end gap-2"><button type="button" onClick={()=>router.back()} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600">Vazgeç</button><button disabled={saving} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Kaydediliyor…":"Görevi kaydet"}</button></div></form></div></main></div>;
}