"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import Sidebar from "@/components/Sidebar";

type Sale = { id:string; amount:string|number; currency:string; status:"ACIK"|"TAMAMLANDI"|"IPTAL"; createdAt:string; closedAt:string|null; note:string|null; commissionRate:string|number|null; officeShareRate:string|number|null; grossCommission:string|number|null; officeShare:string|number|null; consultantShare:string|number|null; customer:{id:string;name:string}; listing:{id:string;code:string;title:string;purpose:string;status:string;price:string|number;currency:string}; offer:{id:string;status:string} };

export default function SaleDetailPage(){
 const params=useParams<{id:string}>(); const [sale,setSale]=useState<Sale|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [note,setNote]=useState(""); const [commissionRate,setCommissionRate]=useState(""); const [officeShareRate,setOfficeShareRate]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{async function load(){try{const r=await fetch("/api/sales",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.message??"Satışlar alınamadı.");const found=(p.sales??[]).find((x:Sale)=>x.id===params.id);if(!found)throw new Error("Satış bulunamadı.");setSale(found);setNote(found.note??"");setCommissionRate(found.commissionRate?.toString()??"");setOfficeShareRate(found.officeShareRate?.toString()??"");}catch(e){setError(e instanceof Error?e.message:"Satış yüklenemedi.");}finally{setLoading(false);}}void load();},[params.id]);
 async function save(data:Record<string,unknown>){setSaving(true);setError(null);try{const r=await fetch("/api/sales/"+params.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const p=await r.json();if(!r.ok)throw new Error(p.message??"Satış güncellenemedi.");setSale(p.sale);setNote(p.sale.note??"");setCommissionRate(p.sale.commissionRate?.toString()??"");setOfficeShareRate(p.sale.officeShareRate?.toString()??"");}catch(e){setError(e instanceof Error?e.message:"Satış güncellenemedi.");}finally{setSaving(false);}}
 if(loading)return <main className="min-h-screen bg-slate-50 md:flex"><Sidebar/><div className="flex-1 p-6">Yükleniyor…</div></main>;
 if(!sale)return <main className="min-h-screen bg-slate-50 md:flex"><Sidebar/><div className="flex-1 p-6"><Link href="/sales" className="font-semibold">← İş Akışı</Link><p className="mt-6 text-rose-600">{error??"Satış bulunamadı."}</p></div></main>;
 const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:sale.currency}); const statusLabel=sale.status==="TAMAMLANDI"?"Tamamlandı":sale.status==="IPTAL"?"İptal":"Açık";
 return <main className="min-h-screen bg-slate-50 md:flex"><Sidebar/><div className="min-w-0 flex-1"><div className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8"><Link href="/sales" className="text-sm font-semibold text-slate-600">← Satışlara dön</Link>
 <header className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Satış kaydı</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">{sale.listing.title}</h1><p className="mt-2 text-sm text-slate-500">{sale.listing.code} · {sale.listing.purpose}</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold">{statusLabel}</span></div><p className="mt-6 text-3xl font-semibold text-slate-950">{money.format(Number(sale.amount))}</p></header>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Taraflar</h2><p className="mt-4 text-xs text-slate-400">Müşteri</p><Link href={"/clients/"+sale.customer.id} className="mt-1 block font-semibold hover:underline">{sale.customer.name}</Link><p className="mt-4 text-xs text-slate-400">Teklif</p><p className="mt-1 text-sm font-semibold">{sale.offer.id} · {sale.offer.status}</p><p className="mt-4 text-xs text-slate-400">Oluşturulma</p><p className="mt-1 text-sm">{new Date(sale.createdAt).toLocaleString("tr-TR")}</p></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Satış durumu</h2><select value={sale.status} disabled={saving} onChange={e=>void save({status:e.target.value})} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold"><option value="ACIK">Açık</option><option value="TAMAMLANDI">Tamamlandı</option><option value="IPTAL">İptal</option></select>{sale.closedAt&&<p className="mt-3 text-xs text-slate-400">Kapanış: {new Date(sale.closedAt).toLocaleString("tr-TR")}</p>}</section>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-semibold">Komisyon ve not</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Komisyon oranı %<input value={commissionRate} onChange={e=>setCommissionRate(e.target.value)} type="number" min="0" max="100" step="0.01" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"/></label><label className="text-sm font-semibold">Ofis payı %<input value={officeShareRate} onChange={e=>setOfficeShareRate(e.target.value)} type="number" min="0" max="100" step="0.01" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal"/></label></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Satış notu" rows={4} className="mt-4 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/><button disabled={saving} onClick={()=>void save({note,commissionRate:commissionRate||undefined,officeShareRate:officeShareRate||undefined})} className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Kaydediliyor…":"Değişiklikleri kaydet"}</button>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Brüt komisyon</p><p className="mt-1 font-semibold">{sale.grossCommission?money.format(Number(sale.grossCommission)):"—"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Ofis payı</p><p className="mt-1 font-semibold">{sale.officeShare?money.format(Number(sale.officeShare)):"—"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Danışman payı</p><p className="mt-1 font-semibold">{sale.consultantShare?money.format(Number(sale.consultantShare)):"—"}</p></div></div></section></div></div></div></main>;
}