"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Sidebar from "@/components/Sidebar";
type Customer={id:string;name:string}; type Listing={id:string;code:string;title:string};
export default function NewSalesShowingPage(){
 const router=useRouter(); const searchParams=useSearchParams();
 const preCustomerId=searchParams.get("customerId")??""; const preListingId=searchParams.get("listingId")??"";
 const [customers,setCustomers]=useState<Customer[]>([]); const [listings,setListings]=useState<Listing[]>([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{void Promise.all([fetch("/api/customers",{cache:"no-store"}).then(r=>r.json()).then(d=>setCustomers(d.customers??[])),fetch("/api/listings?status=AKTIF",{cache:"no-store"}).then(r=>r.json()).then(d=>setListings(d.listings??[]))]).catch(()=>setError("Form verileri alınamadı."));},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget).entries());const payload={...data,attendees:Number(data.attendees||1)};try{const r=await fetch("/api/showings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message??"Gösterim oluşturulamadı.");router.push("/sales");}catch(err){setError(err instanceof Error?err.message:"Gösterim oluşturulamadı.");setSaving(false);}}
 return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar/><main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-3xl"><button type="button" onClick={()=>router.back()} className="mb-5 text-sm font-semibold text-slate-600">← İş Akışına dön</button><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">İş Akışı · Gösterim</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Yeni Gösterim</h1><p className="mt-2 text-sm text-slate-500">Müşteri, portföy ve randevu zamanını tek sayfada oluştur.</p></header>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-sm font-semibold text-slate-700">Müşteri *</span><select required name="customerId" defaultValue={preCustomerId} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Müşteri seçin</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block"><span className="text-sm font-semibold text-slate-700">Portföy *</span><select required name="listingId" defaultValue={preListingId} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Portföy seçin</option>{listings.map(l=><option key={l.id} value={l.id}>{l.code} · {l.title}</option>)}</select></label><label className="block sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Tarih ve saat *</span><input required name="dateTime" type="datetime-local" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><label className="block"><span className="text-sm font-semibold text-slate-700">Katılımcı</span><input name="attendees" type="number" min="1" defaultValue="1" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><label className="block sm:col-span-2"><span className="text-sm font-semibold text-slate-700">Not</span><textarea name="note" rows={4} placeholder="Gösterim notu..." className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label></div></section><div className="flex justify-end gap-2"><button type="button" onClick={()=>router.back()} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600">Vazgeç</button><button disabled={saving} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Kaydediliyor…":"Gösterimi kaydet"}</button></div></form></div></main></div>;
}